services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:nightly
    container_name: wg-easy
    restart: unless-stopped
    ports:
      - 51820:51820/udp
      - 8082:51821/tcp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./data/wg-easy:/etc/wireguard
    environment:
      PASSWORD_HASH: ${PASSWORD_HASH}
      WG_HOST: ${WG_HOST}
      LANG: ${LANG}
