services:
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    restart: unless-stopped
    ports:
      - 8085:80
    volumes:
      - ./data/freshrss-data:/var/www/FreshRSS/data
      - ./data/freshrss-extensions:/var/www/FreshRSS/extensions
    environment:
      TZ: ${TZ}
      CRON_MIN: '3,33'
      TRUSTED_PROXY: ${TRUSTED_PROXY}
